### ISSUE TITLE
Schema diagram in README is not readable in browser with dark mode

### ISSUE THREAD

**Issue by arvindshmicrosoft** [ldbc/ldbc_finbench_datagen#66]
The schema diagram is currently unreadable for those (like me) who use dark mode on their system:

![image](https://github.com/ldbc/ldbc_finbench_datagen/assets/16342666/508cef24-d96d-497d-979c-f251b15998fb)

Please see if you can paste a suitable version which works for both dark and light modes.

**Comment by qishipengqsp** [comment]
Hi, thanks for the suggestion! Will fix this in the next modification.
