### ISSUE TITLE
Problem with run_local.sh

### ISSUE THREAD

**Issue by shizuocheng** [ldbc/ldbc_finbench_datagen#73]
Hello, can you help me look at the problem about run_local.sh?
When I run run_local.sh, the following is displayed:
<img width="1060" alt="image" src="https://github.com/ldbc/ldbc_finbench_datagen/assets/54357688/7a99848f-154c-4e20-a23c-6340f2ca2f47">
However, there is no complete transit data in the out file. 
<img width="589" alt="image" src="https://github.com/ldbc/ldbc_finbench_datagen/assets/54357688/8c627bfd-0677-4489-8402-0ef76cd59796">
The command of run_local.sh is as follows:
<img width="837" alt="image" src="https://github.com/ldbc/ldbc_finbench_datagen/assets/54357688/37aef4ab-98b1-4ded-a312-18a9517396ed">

**Comment by qishipengqsp** [comment]
Hi, thanks for using FinBench datagen first! The problems seems happens in different shells. In the end of line 8 in `run_local.sh`, there should be a backslash marking the continuing line of the python command, which does not happen in my zsh. Your shell tells "未找到命令"/"not found the command" in the output.

I opened #74 to fix this which you can try if it works. Then I will merge it.
