### ISSUE TITLE
Is there generated parameters that can be downloaded?

### ISSUE THREAD

**Issue by ErvinXie** [ldbc/ldbc_finbench_datagen#78]
I already downloaded the generated datasets from Google drive you provided. But it seems that there is no parameters for Read Queries. Can you provide the generated parameters on Google drive?

**Comment by qishipengqsp** [comment]
Hi, the parameters are zipped standalone. And in the first version, we only provide parameters on SF1 and SF10.

- Parameters on SF1: https://drive.google.com/file/d/19ex5BAW1TXa0fPAIQBfUv2Xa4MOj0pVi/view?usp=sharing
- Parameters on SF10: https://drive.google.com/file/d/14qIgiddMHyKFBu_x4-QlzLNxnyOtqTuM/view?usp=drive_link

**Comment by ErvinXie** [comment]
Thank you for this timely reply. It really helps me a lot!
